// ~20 fixtures de producto/variante/imagen cubriendo los casos borde de
// §10 item 2: sin descripción, sin stock en ninguna variante, variante única
// sin ejes, stock parcial por combinación, y un producto en dos categorías a
// la vez (2x1). Además: un producto por cada categoría hoja restante, para
// ejercitar el rollup de categoría padre (§0.1 regla 2). "Blazer" queda sin
// productos a propósito (ver categories.js) — no aparece acá.
//
// Orden canónico de talles con letras (§6.3): alfabético da L,M,S,XL,XS, que
// está mal. Números usan el propio valor como size_order.
const SIZE_ORDER = { XS: 10, S: 20, M: 30, L: 40, XL: 50, XXL: 60, XXXL: 70 };

// Imágenes reales quedan para la Fase 6/7 (upload real con sharp). Acá solo
// se referencian nombres de placeholder — la Fase 2 no procesa imágenes.
function placeholderImage(slug, n, alt, isPrimary) {
  return { filename: `placeholders/${slug}-${n}.jpg`, altText: alt, sortOrder: n, isPrimary };
}

module.exports = [
  {
    // §11 fixture exacto: M/Negro se agota, M sigue vivo vía Blanco, Negro
    // sigue vivo vía L. Doble categoría real + 2x1 (promo N:N, §0.1).
    name: 'Remera Taylor',
    slug: 'remera-taylor',
    description: 'Remera básica de algodón peinado, corte relajado, ideal para combinar con todo.',
    sizeGuide: 'Talle M equivale a busto 92-96cm. Talle L equivale a busto 97-101cm.',
    basePrice: 15990,
    compareAtPrice: null,
    isFeatured: true,
    isActive: true,
    freeShipping: true,
    categories: ['remeras-y-musculosas', '2x1'],
    images: [placeholderImage('remera-taylor', 1, 'Remera Taylor color negro', true)],
    variants: [
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Negro', colorHex: '#1c1917', sku: 'RT-M-NEG', stock: 0 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Blanco', colorHex: '#ffffff', sku: 'RT-M-BLA', stock: 5 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Negro', colorHex: '#1c1917', sku: 'RT-L-NEG', stock: 3 },
    ],
  },
  {
    name: 'Remerón Oversize',
    slug: 'remeron-oversize',
    description: null,
    sizeGuide: null,
    basePrice: 22990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['remerones'],
    images: [placeholderImage('remeron-oversize', 1, 'Remerón oversize color crudo', true)],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Crudo', colorHex: '#e8e2d6', sku: 'RO-S-CRU', stock: 6 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Crudo', colorHex: '#e8e2d6', sku: 'RO-M-CRU', stock: 8 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Crudo', colorHex: '#e8e2d6', sku: 'RO-L-CRU', stock: 4 },
    ],
  },
  {
    name: 'Body Canesú',
    slug: 'body-canesu',
    description: 'Body con canesú bordado y cierre inferior de broches.',
    sizeGuide: 'Consultá la tabla general de talles en la guía de compra.',
    basePrice: 18500,
    compareAtPrice: 23900,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['bodys'],
    images: [placeholderImage('body-canesu', 1, 'Body canesú color blanco', true)],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Blanco', colorHex: '#ffffff', sku: 'BC-S-BLA', stock: 5 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Blanco', colorHex: '#ffffff', sku: 'BC-M-BLA', stock: 7 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Blanco', colorHex: '#ffffff', sku: 'BC-L-BLA', stock: 2 },
    ],
  },
  {
    name: 'Top Cruzado',
    slug: 'top-cruzado',
    description: 'Top cruzado con breteles regulables, ideal para las noches de verano.',
    sizeGuide: null,
    basePrice: 12990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['tops'],
    images: [placeholderImage('top-cruzado', 1, 'Top cruzado color negro', true)],
    variants: [
      { size: null, sizeOrder: 0, color: 'Negro', colorHex: '#1c1917', sku: 'TC-NEG', stock: 1 },
      { size: null, sizeOrder: 0, color: 'Terracota', colorHex: '#b9603f', sku: 'TC-TER', stock: 6 },
    ],
  },
  {
    name: 'Blusa Satinada',
    slug: 'blusa-satinada',
    description: 'Blusa satinada con caída fluida y botones forrados.',
    sizeGuide: 'Corte regular. Si dudás entre dos talles, te recomendamos el más grande.',
    basePrice: 26990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['blusas-y-camisas'],
    images: [
      placeholderImage('blusa-satinada', 1, 'Blusa satinada color verde', true),
      placeholderImage('blusa-satinada', 2, 'Blusa satinada, detalle de botones', false),
    ],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Verde', colorHex: '#4a6b4f', sku: 'BS-S-VER', stock: 4 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Verde', colorHex: '#4a6b4f', sku: 'BS-M-VER', stock: 5 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Verde', colorHex: '#4a6b4f', sku: 'BS-L-VER', stock: 3 },
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Negro', colorHex: '#1c1917', sku: 'BS-S-NEG', stock: 4 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Negro', colorHex: '#1c1917', sku: 'BS-M-NEG', stock: 5 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Negro', colorHex: '#1c1917', sku: 'BS-L-NEG', stock: 3 },
    ],
  },
  {
    // Talles numéricos: el size_order es el propio valor, para que el
    // default-selection dé el mínimo numérico y no el alfabético.
    name: 'Pantalón Palazzo',
    slug: 'pantalon-palazzo',
    description: 'Pantalón palazzo de tiro alto, tela liviana con caída.',
    sizeGuide: null,
    basePrice: 29990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['pantalones'],
    images: [placeholderImage('pantalon-palazzo', 1, 'Pantalón palazzo color beige', true)],
    variants: [
      { size: '36', sizeOrder: 36, color: 'Beige', colorHex: '#c8b174', sku: 'PP-36', stock: 4 },
      { size: '38', sizeOrder: 38, color: 'Beige', colorHex: '#c8b174', sku: 'PP-38', stock: 5 },
      { size: '40', sizeOrder: 40, color: 'Beige', colorHex: '#c8b174', sku: 'PP-40', stock: 2 },
    ],
  },
  {
    name: 'Short Denim',
    slug: 'short-denim',
    description: 'Short de denim clásico con bordes deshilachados.',
    sizeGuide: null,
    basePrice: 17990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['polleras-y-shorts'],
    images: [placeholderImage('short-denim', 1, 'Short denim color azul claro', true)],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Azul claro', colorHex: '#a8c4d8', sku: null, stock: 6 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Azul claro', colorHex: '#a8c4d8', sku: null, stock: 7 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Azul claro', colorHex: '#a8c4d8', sku: null, stock: 3 },
    ],
  },
  {
    // Zero-stock-everywhere: sigue publicado y visible, sin selectores, con
    // el estado "Sin stock" (§3.2 regla 5).
    name: 'Bermuda Cargo',
    slug: 'bermuda-cargo',
    description: 'Bermuda cargo con bolsillos laterales, tela resistente.',
    sizeGuide: null,
    basePrice: 21990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['bermudas'],
    images: [placeholderImage('bermuda-cargo', 1, 'Bermuda cargo color verde militar', true)],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Verde militar', colorHex: '#5a6650', sku: 'BEC-S-VM', stock: 0 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Verde militar', colorHex: '#5a6650', sku: 'BEC-M-VM', stock: 0 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Verde militar', colorHex: '#5a6650', sku: 'BEC-L-VM', stock: 0 },
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Beige', colorHex: '#c8b174', sku: 'BEC-S-BEI', stock: 0 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Beige', colorHex: '#c8b174', sku: 'BEC-M-BEI', stock: 0 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Beige', colorHex: '#c8b174', sku: 'BEC-L-BEI', stock: 0 },
    ],
  },
  {
    // Coincide con el ejemplo de mensaje de WhatsApp de §5.8 (Jean Crop
    // Classic, talle 38/Azul).
    name: 'Jean Crop Classic',
    slug: 'jean-crop-classic',
    description: 'Jean crop de tiro medio, corte recto clásico.',
    sizeGuide: 'Tiro medio, corte recto. Para un fit más ajustado, elegí un talle menos.',
    basePrice: 70700,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: true,
    categories: ['jeans'],
    images: [placeholderImage('jean-crop-classic', 1, 'Jean crop classic color azul', true)],
    variants: [
      { size: '36', sizeOrder: 36, color: 'Azul', colorHex: '#3b5a7a', sku: 'JCC-36-AZ', stock: 5 },
      { size: '38', sizeOrder: 38, color: 'Azul', colorHex: '#3b5a7a', sku: 'JCC-38-AZ', stock: 6 },
      { size: '40', sizeOrder: 40, color: 'Azul', colorHex: '#3b5a7a', sku: 'JCC-40-AZ', stock: 3 },
      { size: '36', sizeOrder: 36, color: 'Negro', colorHex: '#1c1917', sku: 'JCC-36-NEG', stock: 4 },
      { size: '38', sizeOrder: 38, color: 'Negro', colorHex: '#1c1917', sku: 'JCC-38-NEG', stock: 5 },
      { size: '40', sizeOrder: 40, color: 'Negro', colorHex: '#1c1917', sku: 'JCC-40-NEG', stock: 2 },
    ],
  },
  {
    // Variante única, sin talle ni color: valida UNIQUE NULLS NOT DISTINCT
    // (product_id, NULL, NULL) y el caso "sin selectores" de card/ficha.
    name: 'Campera Aviador',
    slug: 'campera-aviador',
    description: 'Campera aviador de gamuza sintética, forro interior cálido.',
    sizeGuide: null,
    basePrice: 54990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['camperas-y-chaquetas'],
    images: [placeholderImage('campera-aviador', 1, 'Campera aviador color marrón', true)],
    variants: [{ size: null, sizeOrder: 0, color: null, colorHex: null, sku: 'CA-UNICA', stock: 4 }],
  },
  {
    name: 'Chaleco Acolchado',
    slug: 'chaleco-acolchado',
    description: 'Chaleco acolchado sin mangas, cierre de cremallera.',
    sizeGuide: null,
    basePrice: 32990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['chalecos'],
    images: [placeholderImage('chaleco-acolchado', 1, 'Chaleco acolchado color negro', true)],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: null, colorHex: null, sku: 'CHA-S', stock: 5 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: null, colorHex: null, sku: 'CHA-M', stock: 6 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: null, colorHex: null, sku: 'CHA-L', stock: 3 },
    ],
  },
  // "Blazer" (categoría hoja de Abrigos) se deja sin ningún producto a
  // propósito: prueba que una categoría sin productos activos desaparece
  // del menú y del mega menú (§4.5, §5.4).
  {
    name: 'Buzo Oversize',
    slug: 'buzo-oversize',
    description: 'Buzo oversize de friza, cuello redondo, puños y cintura elastizados.',
    sizeGuide: null,
    basePrice: 28990,
    compareAtPrice: null,
    isFeatured: true,
    isActive: true,
    freeShipping: false,
    categories: ['buzos-y-sweaters'],
    images: [placeholderImage('buzo-oversize', 1, 'Buzo oversize color gris', true)],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Gris', colorHex: '#a8a196', sku: 'BUO-S-GRI', stock: 5 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Gris', colorHex: '#a8a196', sku: 'BUO-M-GRI', stock: 6 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Gris', colorHex: '#a8a196', sku: 'BUO-L-GRI', stock: 4 },
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Bordo', colorHex: '#7a2e2e', sku: 'BUO-S-BOR', stock: 3 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Bordo', colorHex: '#7a2e2e', sku: 'BUO-M-BOR', stock: 4 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Bordo', colorHex: '#7a2e2e', sku: 'BUO-L-BOR', stock: 2 },
    ],
  },
  {
    name: 'Saco Estructurado',
    slug: 'saco-estructurado',
    description: 'Saco estructurado con hombreras y solapa clásica.',
    sizeGuide: null,
    basePrice: 48990,
    compareAtPrice: 59990,
    isFeatured: false,
    isActive: true,
    freeShipping: true,
    categories: ['sacos'],
    images: [placeholderImage('saco-estructurado', 1, 'Saco estructurado color negro', true)],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Negro', colorHex: '#1c1917', sku: 'SE-S-NEG', stock: 3 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Negro', colorHex: '#1c1917', sku: 'SE-M-NEG', stock: 4 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Negro', colorHex: '#1c1917', sku: 'SE-L-NEG', stock: 2 },
    ],
  },
  {
    name: 'Vestido Satinado Noche',
    slug: 'vestido-satinado-noche',
    description: 'Vestido satinado de fiesta, escote drapeado y caída al piso.',
    sizeGuide: 'Corte ajustado al cuerpo. Consultá medidas exactas por WhatsApp.',
    basePrice: 62990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['noche'],
    images: [placeholderImage('vestido-satinado-noche', 1, 'Vestido satinado de noche color esmeralda', true)],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Esmeralda', colorHex: '#1f5c4a', sku: 'VSN-S-ESM', stock: 4 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Esmeralda', colorHex: '#1f5c4a', sku: 'VSN-M-ESM', stock: 5 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Esmeralda', colorHex: '#1f5c4a', sku: 'VSN-L-ESM', stock: 3 },
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Negro', colorHex: '#1c1917', sku: 'VSN-S-NEG', stock: 4 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Negro', colorHex: '#1c1917', sku: 'VSN-M-NEG', stock: 5 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Negro', colorHex: '#1c1917', sku: 'VSN-L-NEG', stock: 3 },
    ],
  },
  {
    // Eje único (color, sin talle): valida que computeAvailability no exija
    // el eje talle cuando el producto no lo tiene.
    name: 'Musculosa Básica',
    slug: 'musculosa-basica',
    description: 'Musculosa básica de algodón, escote redondo.',
    sizeGuide: null,
    basePrice: 9990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['remeras-y-musculosas'],
    images: [placeholderImage('musculosa-basica', 1, 'Musculosa básica color blanco', true)],
    variants: [
      { size: null, sizeOrder: 0, color: 'Blanco', colorHex: '#ffffff', sku: 'MB-BLA', stock: 2 },
      { size: null, sizeOrder: 0, color: 'Negro', colorHex: '#1c1917', sku: 'MB-NEG', stock: 8 },
      { size: null, sizeOrder: 0, color: 'Gris', colorHex: '#a8a196', sku: 'MB-GRI', stock: 6 },
    ],
  },
  {
    name: 'Pollera Plisada',
    slug: 'pollera-plisada',
    description: 'Pollera plisada midi, cintura elastizada.',
    sizeGuide: null,
    basePrice: 24990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['polleras-y-shorts'],
    images: [placeholderImage('pollera-plisada', 1, 'Pollera plisada color mostaza', true)],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Mostaza', colorHex: '#c8922e', sku: 'POP-S-MOS', stock: 5 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Mostaza', colorHex: '#c8922e', sku: 'POP-M-MOS', stock: 2 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Mostaza', colorHex: '#c8922e', sku: 'POP-L-MOS', stock: 4 },
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Negro', colorHex: '#1c1917', sku: 'POP-S-NEG', stock: 6 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Negro', colorHex: '#1c1917', sku: 'POP-M-NEG', stock: 5 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Negro', colorHex: '#1c1917', sku: 'POP-L-NEG', stock: 3 },
    ],
  },
  {
    name: 'Camisa Oxford',
    slug: 'camisa-oxford',
    description: null,
    sizeGuide: null,
    basePrice: 27990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['blusas-y-camisas'],
    images: [placeholderImage('camisa-oxford', 1, 'Camisa oxford color celeste', true)],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Celeste', colorHex: '#a8c4d8', sku: 'CO-S-CEL', stock: 5 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Celeste', colorHex: '#a8c4d8', sku: 'CO-M-CEL', stock: 6 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Celeste', colorHex: '#a8c4d8', sku: 'CO-L-CEL', stock: 4 },
    ],
  },
  {
    // Variante única Y sin stock a la vez: combina dos casos borde en un
    // mismo producto (§3.2 regla 5 con un solo axis-less variant).
    name: 'Top Básico',
    slug: 'top-basico',
    description: 'Top básico lycra, tiras finas ajustables.',
    sizeGuide: null,
    basePrice: 8990,
    compareAtPrice: null,
    isFeatured: false,
    isActive: true,
    freeShipping: false,
    categories: ['tops'],
    images: [placeholderImage('top-basico', 1, 'Top básico color negro', true)],
    variants: [{ size: null, sizeOrder: 0, color: null, colorHex: null, sku: 'TB-UNICA', stock: 0 }],
  },
  {
    name: 'Vestido Fiesta Bordado',
    slug: 'vestido-fiesta-bordado',
    description: 'Vestido de fiesta con bordado artesanal en el escote.',
    sizeGuide: 'Corte semi ajustado. Para un fit más holgado, elegí un talle más.',
    basePrice: 74990,
    compareAtPrice: 89990,
    isFeatured: true,
    isActive: true,
    freeShipping: true,
    categories: ['noche'],
    images: [placeholderImage('vestido-fiesta-bordado', 1, 'Vestido de fiesta bordado color negro', true)],
    variants: [
      { size: 'S', sizeOrder: SIZE_ORDER.S, color: 'Negro', colorHex: '#1c1917', sku: 'VFB-S-NEG', stock: 3 },
      { size: 'M', sizeOrder: SIZE_ORDER.M, color: 'Negro', colorHex: '#1c1917', sku: 'VFB-M-NEG', stock: 4 },
      { size: 'L', sizeOrder: SIZE_ORDER.L, color: 'Negro', colorHex: '#1c1917', sku: 'VFB-L-NEG', stock: 2 },
    ],
  },
];
